"""The public surface is classified and checked against the 0.8.1 baseline.

Two independent guarantees are under test:

1. the documented surface map (`tests/compat/public-api.json`) is the source of
   truth for what is public — an accidental addition or removal fails
   `tests/test_public_api.py`, and the baseline records how each name is
   shaped;
2. `scripts/api_compat.py` detects every incompatible change class the
   compatibility policy promises — removed names, moved names, incompatible
   signatures, changed enum values, changed public fields — deterministically.

The 0.8.1 baseline was generated by `scripts/api_compat.py describe --write`
against the distribution built from the `v0.8.1` tag, never from this tree.
"""

from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

import pytest

ROOT = Path(__file__).resolve().parents[1]
SURFACE_PATH = ROOT / "tests" / "compat" / "public-api.json"
BASELINE_PATH = ROOT / "tests" / "compat" / "api-baseline-0.8.1.json"


def _tool() -> Any:
    spec = importlib.util.spec_from_file_location("api_compat", ROOT / "scripts" / "api_compat.py")
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _surface() -> dict[str, Any]:
    return json.loads(SURFACE_PATH.read_text(encoding="utf-8"))


def _baseline() -> dict[str, Any]:
    return json.loads(BASELINE_PATH.read_text(encoding="utf-8"))


def _document(modules: dict[str, Any]) -> dict[str, Any]:
    return {"format_version": 1, "package_version": "test", "modules": modules}


def _function(*params: tuple[str, str, bool]) -> dict[str, Any]:
    return {
        "kind": "function",
        "params": [
            {"name": name, "kind": kind, "default": default} for name, kind, default in params
        ],
    }


def _violation_kinds(report: dict[str, Any]) -> list[tuple[str, str, str]]:
    return [(item["kind"], item["module"], item["name"]) for item in report["violations"]]


class TestBaseline:
    def test_the_baseline_was_produced_by_the_released_0_8_1_implementation(self) -> None:
        baseline = _baseline()

        assert baseline["package_version"] == "0.8.1"
        assert baseline["format_version"] == 1

    def test_every_baseline_name_is_still_classified(self) -> None:
        """A name silently dropped from the source of truth is a removal attempt."""

        surface = _surface()
        baseline = _baseline()

        for module, names in baseline["modules"].items():
            for name in names:
                assert name in surface["modules"].get(module, {}), (module, name)

    def test_every_classified_name_has_a_valid_stability_class(self) -> None:
        for module, names in _surface()["modules"].items():
            for name, meta in names.items():
                assert meta.get("stability") in {"stable", "provisional"}, (module, name)

    def test_the_current_surface_is_compatible_with_the_baseline(self) -> None:
        tool = _tool()
        report = tool.compare_documents(_baseline(), tool.describe_surface(_surface()))

        assert report["violations"] == []
        assert report["compatible"] is True

    def test_description_is_deterministic(self) -> None:
        tool = _tool()
        first = tool.describe_surface(_surface())
        second = tool.describe_surface(_surface())

        assert json.dumps(first, sort_keys=True) == json.dumps(second, sort_keys=True)


class TestIncompatibleChangeDetection:
    def test_a_removed_public_name_is_detected(self) -> None:
        tool = _tool()
        old = _document({"chassis": {"Harness": _function()}})
        new = _document({"chassis": {}})

        report = tool.compare_documents(old, new)

        assert _violation_kinds(report) == [("removed_name", "chassis", "Harness")]
        assert report["compatible"] is False

    def test_a_moved_public_name_is_detected(self) -> None:
        tool = _tool()
        old = _document({"chassis": {"Harness": _function()}})
        new = _document({"chassis.runtime": {"Harness": _function()}, "chassis": {}})

        report = tool.compare_documents(old, new)

        assert _violation_kinds(report) == [("moved_name", "chassis", "Harness")]
        assert report["violations"][0]["to"] == "chassis.runtime"

    @pytest.mark.parametrize(
        ("old_params", "new_params"),
        [
            ([("a", "POSITIONAL_OR_KEYWORD", False)], []),
            ([("a", "POSITIONAL_OR_KEYWORD", False)], [("a", "KEYWORD_ONLY", False)]),
            ([("a", "POSITIONAL_OR_KEYWORD", True)], [("a", "POSITIONAL_OR_KEYWORD", False)]),
            ([], [("a", "POSITIONAL_OR_KEYWORD", False)]),
        ],
        ids=["removed", "changed-kind", "lost-default", "added-required"],
    )
    def test_an_incompatible_signature_is_detected(
        self,
        old_params: list[tuple[str, str, bool]],
        new_params: list[tuple[str, str, bool]],
    ) -> None:
        tool = _tool()
        old = _document({"chassis": {"run": _function(*old_params)}})
        new = _document({"chassis": {"run": _function(*new_params)}})

        report = tool.compare_documents(old, new)

        assert _violation_kinds(report) == [("changed_signature", "chassis", "run")]

    def test_a_removed_class_method_is_detected(self) -> None:
        tool = _tool()
        harness_with_stop = {"kind": "class", "params": [], "methods": {"stop": {"params": []}}}
        harness_without_stop = {"kind": "class", "params": [], "methods": {}}
        old = _document({"chassis": {"Harness": harness_with_stop}})
        new = _document({"chassis": {"Harness": harness_without_stop}})

        report = tool.compare_documents(old, new)

        assert _violation_kinds(report) == [("removed_method", "chassis", "Harness")]

    @pytest.mark.parametrize(
        ("old_members", "new_members"),
        [
            ({"A": "a"}, {}),
            ({"A": "a"}, {"A": "b"}),
        ],
        ids=["member-removed", "value-changed"],
    )
    def test_a_changed_enum_value_is_detected(
        self, old_members: dict[str, str], new_members: dict[str, str]
    ) -> None:
        tool = _tool()
        old = _document({"chassis": {"Mode": {"kind": "enum", "members": old_members}}})
        new = _document({"chassis": {"Mode": {"kind": "enum", "members": new_members}}})

        report = tool.compare_documents(old, new)

        assert _violation_kinds(report) == [("changed_enum_value", "chassis", "Mode")]

    @pytest.mark.parametrize(
        ("old_fields", "new_fields"),
        [
            ({"x": {"type": "int", "default": False}}, {}),
            ({"x": {"type": "int", "default": False}}, {"x": {"type": "str", "default": False}}),
            ({"x": {"type": "int", "default": True}}, {"x": {"type": "int", "default": False}}),
            ({}, {"x": {"type": "int", "default": False}}),
        ],
        ids=["removed", "retyped", "lost-default", "added-required"],
    )
    def test_a_changed_public_field_is_detected(
        self, old_fields: dict[str, Any], new_fields: dict[str, Any]
    ) -> None:
        tool = _tool()
        old = _document({"chassis": {"Record": {"kind": "dataclass", "fields": old_fields}}})
        new = _document({"chassis": {"Record": {"kind": "dataclass", "fields": new_fields}}})

        report = tool.compare_documents(old, new)

        assert _violation_kinds(report) == [("changed_field", "chassis", "Record")]

    def test_additive_changes_are_compatible(self) -> None:
        tool = _tool()
        old = _document({"chassis": {"run": _function(("a", "POSITIONAL_OR_KEYWORD", False))}})
        run_with_default = _function(
            ("a", "POSITIONAL_OR_KEYWORD", False), ("b", "KEYWORD_ONLY", True)
        )
        new = _document({"chassis": {"run": run_with_default, "preview": _function()}})

        report = tool.compare_documents(old, new)

        assert report["compatible"] is True
        assert report["additions"] == [{"module": "chassis", "name": "preview"}]

    def test_reports_are_deterministically_ordered(self) -> None:
        tool = _tool()
        old = _document({"chassis": {"b": _function(), "a": _function()}})
        new = _document({"chassis": {}})

        first = tool.compare_documents(old, new)
        second = tool.compare_documents(old, new)

        assert json.dumps(first, sort_keys=True) == json.dumps(second, sort_keys=True)
        assert [item["name"] for item in first["violations"]] == ["a", "b"]


def test_the_check_command_reports_incompatibility_with_a_non_zero_exit() -> None:
    """The CLI behaves the same way CI relies on."""

    ok = subprocess.run(
        [sys.executable, "scripts/api_compat.py", "check", str(BASELINE_PATH)],
        capture_output=True,
        text=True,
        cwd=ROOT,
        check=False,
    )
    assert ok.returncode == 0, ok.stdout + ok.stderr

    synthetic = json.loads(BASELINE_PATH.read_text(encoding="utf-8"))
    # A name the installed package does not have simulates a later removal.
    synthetic["modules"]["chassis"]["Harness"] = {
        "kind": "class",
        "params": [],
        "methods": {"vanished": {"params": []}},
    }
    synthetic_path = BASELINE_PATH.parent / "_synthetic-baseline.json"
    synthetic_path.write_text(json.dumps(synthetic), encoding="utf-8")
    try:
        changed = subprocess.run(
            [sys.executable, "scripts/api_compat.py", "check", str(synthetic_path)],
            capture_output=True,
            text=True,
            cwd=ROOT,
            check=False,
        )
    finally:
        synthetic_path.unlink(missing_ok=True)

    assert changed.returncode == 1
    report = json.loads(changed.stdout)
    assert report["compatible"] is False
    assert any(
        item["kind"] == "removed_method" and item["name"] == "Harness"
        for item in report["violations"]
    )
